version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip3 install pytest
      - ls -l 
  pre_build:
   commands:
       - echo "Hello World!"
       - pytest -v tests/test_main.py
       - aws help